import { z } from "zod";

export const highlightSchema = z.object({
  text: z.string(),
  position: z.number(),
});

export type Highlight = z.infer<typeof highlightSchema>;

export const savedItemSchema = z.object({
  id: z.string(),
  userId: z.string(),
  url: z.string().refine((val) => {
    try {
      const url = new URL(val);
      return ["http:", "https:", "file:"].includes(url.protocol);
    } catch {
      return false;
    }
  }, { message: "Invalid URL" }),
  title: z.string(),
  content: z.string(),
  summary: z.string(),
  tags: z.array(z.string()),
  concepts: z.array(z.string()),
  savedAt: z.number(),
  lastAccessed: z.number(),
  readingProgress: z.number().min(0).max(100),
  notes: z.string(),
  highlights: z.array(highlightSchema),
  connections: z.array(z.string()),
  connectionReasons: z.record(z.string(), z.string()).optional(),
  expiresAt: z.number().nullable(),
  domain: z.string(),
  favicon: z.string().optional(),
  imageUrl: z.string().optional(),
  isRead: z.boolean(),
});

export type SavedItem = z.infer<typeof savedItemSchema>;

export const insertSavedItemSchema = z.object({
  url: z.string().refine((val) => {
    try {
      const url = new URL(val);
      return ["http:", "https:", "file:"].includes(url.protocol);
    } catch {
      return false;
    }
  }, { message: "Invalid URL. Must be http, https, or file protocol." }),
});

export type InsertSavedItem = z.infer<typeof insertSavedItemSchema>;

export const updateSavedItemSchema = savedItemSchema.partial().omit({ id: true });

export type UpdateSavedItem = z.infer<typeof updateSavedItemSchema>;

export const collectionSchema = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  itemIds: z.array(z.string()),
  isAutoGenerated: z.boolean(),
  createdAt: z.number(),
  color: z.string(),
});

export type Collection = z.infer<typeof collectionSchema>;

export const insertCollectionSchema = collectionSchema.omit({
  id: true,
  createdAt: true,
});

export type InsertCollection = z.infer<typeof insertCollectionSchema>;

export const conceptSchema = z.object({
  id: z.string(),
  name: z.string(),
  itemIds: z.array(z.string()),
  relatedConcepts: z.array(z.string()),
});

export type Concept = z.infer<typeof conceptSchema>;

export const chatMessageSchema = z.object({
  id: z.string(),
  role: z.enum(["user", "assistant"]),
  content: z.string(),
  timestamp: z.number(),
});

export type ChatMessage = z.infer<typeof chatMessageSchema>;

export const chatRequestSchema = z.object({
  message: z.string().min(1),
  items: z.array(z.object({
    id: z.string(),
    title: z.string(),
    summary: z.string(),
    tags: z.array(z.string()),
    concepts: z.array(z.string()),
    url: z.string(),
  })).optional(),
});

export type ChatRequest = z.infer<typeof chatRequestSchema>;

export * from "./models/auth";
