import { useMemo } from "react";
import { motion } from "framer-motion";
import { FolderOpen, Plus, Sparkles } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useEden } from "@/lib/store";
import { SavedItemCard } from "./SavedItemCard";
import type { Collection } from "@shared/schema";

export function CollectionsView() {
  const { items, collections } = useEden();

  const autoGeneratedCollections = useMemo(() => {
    const tagGroups = new Map<string, string[]>();
    const conceptGroups = new Map<string, string[]>();

    items.forEach((item) => {
      item.tags.forEach((tag) => {
        const existing = tagGroups.get(tag) || [];
        existing.push(item.id);
        tagGroups.set(tag, existing);
      });

      item.concepts.forEach((concept) => {
        const existing = conceptGroups.get(concept) || [];
        existing.push(item.id);
        conceptGroups.set(concept, existing);
      });
    });

    const generatedCollections: Collection[] = [];
    const colors = [
      "hsl(153, 24%, 46%)",
      "hsl(30, 80%, 60%)",
      "hsl(215, 60%, 55%)",
      "hsl(280, 50%, 55%)",
      "hsl(340, 70%, 55%)",
    ];

    Array.from(tagGroups.entries())
      .filter(([_, itemIds]) => itemIds.length >= 2)
      .sort((a, b) => b[1].length - a[1].length)
      .slice(0, 5)
      .forEach(([tag, itemIds], index) => {
        generatedCollections.push({
          id: `auto-tag-${tag}`,
          name: tag,
          description: `Items tagged with "${tag}"`,
          itemIds,
          isAutoGenerated: true,
          createdAt: Date.now(),
          color: colors[index % colors.length],
        });
      });

    Array.from(conceptGroups.entries())
      .filter(([_, itemIds]) => itemIds.length >= 2)
      .sort((a, b) => b[1].length - a[1].length)
      .slice(0, 5)
      .forEach(([concept, itemIds], index) => {
        generatedCollections.push({
          id: `auto-concept-${concept}`,
          name: concept,
          description: `Items about "${concept}"`,
          itemIds,
          isAutoGenerated: true,
          createdAt: Date.now(),
          color: colors[(index + 2) % colors.length],
        });
      });

    return generatedCollections;
  }, [items]);

  const allCollections = [...collections, ...autoGeneratedCollections];

  if (allCollections.length === 0) {
    return (
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="flex flex-col items-center justify-center py-16 text-center"
      >
        <div className="w-16 h-16 rounded-2xl bg-muted flex items-center justify-center mb-4">
          <FolderOpen className="w-8 h-8 text-muted-foreground" />
        </div>
        <h3 className="text-lg font-semibold mb-2">No collections yet</h3>
        <p className="text-muted-foreground max-w-sm mb-6">
          Save more content and Eden will automatically group related items into smart collections.
        </p>
      </motion.div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-lg font-semibold">Smart Collections</h2>
          <p className="text-sm text-muted-foreground">
            Automatically organized based on your saved content
          </p>
        </div>
      </div>

      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
        {allCollections.map((collection, index) => {
          const collectionItems = items.filter((item) =>
            collection.itemIds.includes(item.id)
          );

          return (
            <motion.div
              key={collection.id}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.05 }}
            >
              <Card className="hover-elevate active-elevate-2 cursor-pointer h-full">
                <CardHeader className="pb-3">
                  <div className="flex items-start justify-between">
                    <div
                      className="w-10 h-10 rounded-xl flex items-center justify-center"
                      style={{ backgroundColor: `${collection.color}20` }}
                    >
                      {collection.isAutoGenerated ? (
                        <Sparkles className="w-5 h-5" style={{ color: collection.color }} />
                      ) : (
                        <FolderOpen className="w-5 h-5" style={{ color: collection.color }} />
                      )}
                    </div>
                    {collection.isAutoGenerated && (
                      <Badge variant="secondary" className="text-2xs">
                        Auto
                      </Badge>
                    )}
                  </div>
                  <CardTitle className="text-base mt-3">{collection.name}</CardTitle>
                  <p className="text-xs text-muted-foreground">{collection.description}</p>
                </CardHeader>
                <CardContent>
                  <div className="space-y-2">
                    {collectionItems.slice(0, 3).map((item) => (
                      <div
                        key={item.id}
                        className="flex items-center gap-2 p-2 rounded-lg bg-muted/50"
                      >
                        {item.favicon && (
                          <img src={item.favicon} alt="" className="w-4 h-4 rounded" />
                        )}
                        <span className="text-sm truncate flex-1">{item.title}</span>
                      </div>
                    ))}
                    {collectionItems.length > 3 && (
                      <p className="text-xs text-muted-foreground text-center pt-1">
                        +{collectionItems.length - 3} more items
                      </p>
                    )}
                  </div>
                </CardContent>
              </Card>
            </motion.div>
          );
        })}
      </div>
    </div>
  );
}
