import { useMemo } from "react";
import { motion } from "framer-motion";
import { FolderOpen, Sparkles } from "lucide-react";
import { useEden } from "@/lib/store";
import type { Collection } from "@shared/schema";

const colors = [
  "hsl(160, 50%, 42%)",
  "hsl(200, 70%, 50%)",
  "hsl(280, 60%, 55%)",
  "hsl(45, 85%, 50%)",
  "hsl(340, 70%, 55%)",
];

export function CollectionsView() {
  const { items, collections, setSelectedItem } = useEden();

  const autoGeneratedCollections = useMemo(() => {
    const tagGroups = new Map<string, string[]>();

    items.forEach((item) => {
      item.tags.forEach((tag) => {
        const existing = tagGroups.get(tag) || [];
        existing.push(item.id);
        tagGroups.set(tag, existing);
      });
    });

    const generatedCollections: Collection[] = [];

    Array.from(tagGroups.entries())
      .filter(([_, itemIds]) => itemIds.length >= 1)
      .sort((a, b) => b[1].length - a[1].length)
      .slice(0, 8)
      .forEach(([tag, itemIds], index) => {
        generatedCollections.push({
          id: `auto-tag-${tag}`,
          name: tag,
          description: `${itemIds.length} items`,
          itemIds,
          isAutoGenerated: true,
          createdAt: Date.now(),
          color: colors[index % colors.length],
        });
      });

    return generatedCollections;
  }, [items]);

  const allCollections = [...collections, ...autoGeneratedCollections];

  if (allCollections.length === 0) {
    return (
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="flex flex-col items-center justify-center py-24 text-center"
      >
        <div className="w-24 h-24 sphere-glass opacity-40 mb-6" />
        <h3 className="font-serif text-2xl mb-3">No collections yet</h3>
        <p className="text-muted-foreground max-w-sm">
          Save more content and Eden will automatically organize them into collections.
        </p>
      </motion.div>
    );
  }

  return (
    <div className="space-y-8">
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
        {allCollections.map((collection, index) => {
          const collectionItems = items.filter((item) =>
            collection.itemIds.includes(item.id)
          );

          return (
            <motion.div
              key={collection.id}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.05 }}
              className="bento-card p-5 card-hover-lift cursor-pointer"
            >
              <div className="flex items-start justify-between mb-4">
                <div
                  className="w-10 h-10 rounded-xl flex items-center justify-center"
                  style={{ backgroundColor: `${collection.color}20` }}
                >
                  {collection.isAutoGenerated ? (
                    <Sparkles className="w-5 h-5" style={{ color: collection.color }} />
                  ) : (
                    <FolderOpen className="w-5 h-5" style={{ color: collection.color }} />
                  )}
                </div>
                <span className="text-xs text-muted-foreground bg-muted px-2 py-1 rounded-full">
                  {collection.itemIds.length}
                </span>
              </div>

              <h3 className="font-serif text-lg mb-1">{collection.name}</h3>
              <p className="text-xs text-muted-foreground mb-4">{collection.description}</p>

              <div className="space-y-2">
                {collectionItems.slice(0, 3).map((item) => (
                  <div
                    key={item.id}
                    className="flex items-center gap-2 p-2 rounded-lg hover:bg-muted/50 transition-colors"
                    onClick={(e) => {
                      e.stopPropagation();
                      setSelectedItem(item);
                    }}
                  >
                    {item.favicon && (
                      <img src={item.favicon} alt="" className="w-4 h-4 rounded" />
                    )}
                    <span className="text-sm truncate flex-1">{item.title}</span>
                  </div>
                ))}
                {collectionItems.length > 3 && (
                  <p className="text-xs text-muted-foreground text-center pt-1">
                    +{collectionItems.length - 3} more
                  </p>
                )}
              </div>
            </motion.div>
          );
        })}
      </div>
    </div>
  );
}
